export const colors = {
  primary: "#cf952c",
  primary_light: "#f8efe0",
  secondary: "#9d948f",
  secondary_light: "#",
  dark_strong: "#",
  dark_light: "#",
  dark_gray: "#",
  dark_gray_light: "#",
  dark_white_strong: "#",
  dark_white_light: "#",
  blue: "#",
  blue_light: "#",
  green: "#",
  green_light: "#",
  orange: "#",
  orange_light: "#",
  red: "#",
  red_light: "#",
  blue: "#",
  blue_light: "#",
  white: "#fff",
};
